- defaultTab: nodes
  description: |-
    Test the Nginx configuration syntax

    This Job tests the Nginx configuration syntax using the command **`nginx -t`** on a remote Linux node.

    See the [**Project Readme**](/project/automated-diagnostics/home) for recommended tours on how to add remote-nodes and configure connectivity to them using methods such as SSH or Systems Manager (SSM).
  executionEnabled: true
  group: Nginx
  id: 46e4295c-a873-4dc9-8d21-ef605d7e73b5
  loglevel: INFO
  name: Test Nginx Configuration
  nodeFilterEditable: true
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ${option.node_filter}
  nodesSelectedByDefault: true
  options:
  - hidden: true
    label: Node Filter
    name: node_filter
    value: hostname
  - description: |-
      ID of the PagerDuty incident that should receive the diagnostics queried from this automation.
      This field is **_not_** required to invoke this Job.
    label: PagerDuty Incident ID
    name: pd_incident_id
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Check Configuration Syntax on Remote Node
      exec: nginx -t
      plugins:
        LogFilter:
        - config:
            captureMultipleKeysValues: 'false'
            hideOutput: 'false'
            logData: 'true'
            name: nginx_config
            regex: (.*)
          type: key-value-data-multilines
    - configuration:
        api_token: keys/project/automated-diagnostics/pd-api-token
        incident_id: ${option.pd_incident_id}
        note: Nginx Config Status:\n ${data.nginx_config*}
      description: Send Diagnostics to PagerDuty
      errorhandler:
        configuration:
          text: Please provide PagerDuty API token and Incident ID to send diagnostics
            to Incident.
        keepgoingOnSuccess: true
        nodeStep: false
        type: progress-badge
      nodeStep: false
      type: pd-note-step
    keepgoing: false
    strategy: node-first
  tags: nginx
  uuid: 46e4295c-a873-4dc9-8d21-ef605d7e73b5

