- defaultTab: nodes
  description: |-
    Test the Nginx configuration syntax

    This Job tests the Nginx configuration syntax using the command `nginx -t` on a remote Linux node.

    See the **Readme** for instructions on how to add remote-nodes and configure connectivity to them using methods such as SSH or Systems Manager (SSM).
    ---
    For adding remote-nodes, see the **Configure EC2 Inventory** tour.

    See the **Configuring Systems Manager** or **Configure SSH Connectivity** tours for guides on how to invoke the commands in this Job on remote Nodes.  These will also walk you through how to target specific nodes upon execution.

    And see the **Send Diagnostics to PagerDuty** tour for sending the output of the Job to PagerDuty incidents.
  executionEnabled: true
  group: Nginx
  id: 46e4295c-a873-4dc9-8d21-ef605d7e73b5
  loglevel: INFO
  name: Test Nginx Configuration
  nodeFilterEditable: true
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ${option.node_filter}
  nodesSelectedByDefault: true
  options:
  - hidden: true
    label: Node Filter
    name: node_filter
    value: hostname
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Check Configuration Syntax on Remote Node
      exec: nginx -t
    keepgoing: false
    strategy: node-first
  tags: nginx
  uuid: 46e4295c-a873-4dc9-8d21-ef605d7e73b5

