- defaultTab: nodes
  description: |-
    Describe an individual Pod in a specified namespace.

    This Job uses `kubectl` to retrieve the status of an individual Pod in a particular namespace.

    If using PagerDuty Runbook Automation (SaaS), then this Job is designed to be run on an [**Enterprise Runner**](https://docs.rundeck.com/docs/administration/runner/#architecture). Follow the documentation and install the Runner in a location that can communicate with your Kubernetes cluster.
  executionEnabled: true
  group: Kubernetes
  id: 18297716-9412-40d7-ac47-0eb80f0d6df9
  loglevel: INFO
  name: Describe Specific Pod
  nodeFilterEditable: false
  notification:
    onfailure:
      plugin:
        configuration:
          incident_id: ${option.pd_incident_id}
          note: 'Automated diagnostics job did not complete.  For full details, click
              here: ${job.url}#output'
        type: pd-note-incident-notification
  notifyAvgDurationThreshold: null
  options:
  - description: Specify the Kubernetes Namespace
    label: Kubernetes Namespace
    name: namespace
    required: true
    value: default
  - description: |-
      ID of the PagerDuty incident that should receive the diagnostics queried from this automation.
      This field is **_not_** required to invoke this Job.
    label: PagerDuty Incident ID
    name: pd_incident_id
  - description: The name of the individual Pod to describe.
    label: Pod Name
    name: pod_name
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Describe Pod in Namespace
      exec: kubectl describe pod ${option.pod_name} -n ${option.namespace}
      plugins:
        LogFilter:
        - config:
            captureMultipleKeysValues: 'false'
            hideOutput: 'false'
            logData: 'true'
            name: describe_pod
            regex: (.*)
          type: key-value-data-multilines
    - configuration:
        incident_id: ${option.pd_incident_id}
        note: Pod Description:\n ${data.describe_pod*}
      description: Send Diagnostics to PagerDuty
      errorhandler:
        configuration:
          text: Please provide PagerDuty API token and Incident ID to send diagnostics
            to Incident.
        keepgoingOnSuccess: true
        nodeStep: false
        type: progress-badge
      nodeStep: false
      type: pd-note-step
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: 18297716-9412-40d7-ac47-0eb80f0d6df9

