- defaultTab: nodes
  description: |-
    Describe a Replicaset in a specified Namespace

    This Job describes a Replicaset in a specified namespace.  This is useful for scenarios where the Resource Quotes have been exceeded.

    If using PagerDuty Runbook Automation (SaaS), then this Job is designed to be run on an [**Enterprise Runner**](https://docs.rundeck.com/docs/administration/runner/#architecture). Follow the documentation and install the Runner in a location that can communicate with your Kubernetes cluster.
  executionEnabled: true
  group: Kubernetes
  id: 9d0da58c-29f7-42df-aa2f-262c3d6aa290
  loglevel: INFO
  name: Describe Replicaset
  nodeFilterEditable: false
  notification:
    onfailure:
      plugin:
        configuration:
          incident_id: ${option.pd_incident_id}
          note: 'Automated Diagnostics job "${job.project}/${job.group}/${job.name}"
            Failed for incident "${option.pd_incident_id}".   See the full Process Automation
            log at: ${job.url}#output'
        type: pd-note-incident-notification
    onstart:
      plugin:
        configuration:
          incident_id: ${option.pd_incident_id}
          note: 'Automated Diagnostics job "${job.project}/${job.group}/${job.name}"
            Started for incident "${option.pd_incident_id}".   See the full Process Automation
            log at: ${job.url}#output'
        type: pd-note-incident-notification
    onsuccess:
      plugin:
        configuration:
          incident_id: ${option.pd_incident_id}
          note: 'Automated Diagnostics job "${job.project}/${job.group}/${job.name}"
            Succeeded for incident "${option.pd_incident_id}".   See the full Process Automation
            log at: ${job.url}#output'
        type: pd-note-incident-notification
  notifyAvgDurationThreshold: null
  options:
  - description: Namespace where the Replicaset Resides
    label: Namespace
    name: namespace
    required: true
    value: default
  - description: |-
      ID of the PagerDuty incident that should receive the diagnostics queried from this automation.
      This field is **_not_** required to invoke this Job.
    label: PagerDuty Incident ID
    name: pd_incident_id
  - description: Name of the Replicaset in the specified Namespace.
    label: Replicaset Name
    name: replicaset_name
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Describe Replicaset in specified Namespace
      exec: 'kubectl describe replicaset ${option.replicaset_name} -n ${option.namespace} '
      plugins:
        LogFilter:
        - config:
            captureMultipleKeysValues: 'false'
            hideOutput: 'false'
            logData: 'true'
            name: describe_replicaset
            regex: (.*)
          type: key-value-data-multilines
    - configuration:
        incident_id: ${option.pd_incident_id}
        note: Kubernetes Replicaset:\n ${data.describe_replicaset*}
      description: Send Diagnostics to PagerDuty
      errorhandler:
        configuration:
          text: Please provide PagerDuty API token and Incident ID to send diagnostics
            to Incident.
        keepgoingOnSuccess: true
        nodeStep: false
        type: progress-badge
      nodeStep: false
      type: pd-note-step
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: 9d0da58c-29f7-42df-aa2f-262c3d6aa290

