- defaultTab: nodes
  description: |-
    Describe specific Deployment in a particular Namespace

    This Job describes a particular Deployment.  This is useful for troubleshooting events when a deployment fails because there is not enough CPU or Memory to deplopy additional pods.

    If using PagerDuty Runbook Automation (SaaS), then this Job is designed to be run on an [**Enterprise Runner**](https://docs.rundeck.com/docs/administration/runner/#architecture). Follow the documentation and install the Runner in a location that can communicate with your Kubernetes cluster.
  executionEnabled: true
  group: Kubernetes
  id: 47ed6fd5-1bc2-4628-95fb-1a37b274c5a9
  loglevel: INFO
  name: Describe Deployment
  nodeFilterEditable: false
  options:
  - description: Name of the Deployment in the Kubernetes Namespace.
    label: Deployment Name
    name: deployment_name
    required: true
  - description: Namespace where the particular Deployment resides.
    label: Namespace
    name: namespace
    required: true
    value: default
  - description: |-
      ID of the PagerDuty incident that should receive the diagnostics queried from this automation.
      This field is **_not_** required to invoke this Job.
    label: PagerDuty Incident ID
    name: pd_incident_id
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Describe Deployment in Namespace
      exec: 'kubectl describe -n ${option.namespace} deployment/${option.deployment_name} '
      plugins:
        LogFilter:
        - config:
            captureMultipleKeysValues: 'false'
            hideOutput: 'false'
            logData: 'true'
            name: describe_deployment
            regex: (.*)
          type: key-value-data-multilines
    - configuration:
        api_token: keys/project/automated-diagnostics/pd-api-token
        incident_id: ${option.pd_incident_id}
        note: Kubernetes Deployment:\n ${data.describe_deployment*}
      description: Send Diagnostics to PagerDuty
      errorhandler:
        configuration:
          text: Please provide PagerDuty API token and Incident ID to send diagnostics
            to Incident.
        keepgoingOnSuccess: true
        nodeStep: false
        type: progress-badge
      nodeStep: false
      type: pd-note-step
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: 47ed6fd5-1bc2-4628-95fb-1a37b274c5a9

