- defaultTab: nodes
  description: "Send a command to an individual pod in a specific namespace.\n\nThis\
    \ Job sends a command to a pod in a specified namespace.  \n\nIf using PagerDuty\
    \ Runbook Automation (SaaS), then this Job is designed to be run on an [**Enterprise\
    \ Runner**](https://docs.rundeck.com/docs/administration/runner/#architecture).\
    \ Follow the documentation and install the Runner in a location that can communicate\
    \ with your Kubernetes cluster."
  executionEnabled: true
  group: Kubernetes
  id: b02ca591-7605-4e1a-abf9-ce54d874d336
  loglevel: INFO
  name: Execute Command in Pod
  nodeFilterEditable: false
  options:
  - description: This will be executed as `/bin/bash` within the specified container.
    label: Command
    name: command
    required: true
  - description: Namespace where the Pod resides
    label: Namespace
    name: namespace
    required: true
    value: default
  - description: Pod to send specific command to.
    label: Pod Name
    name: pod_name
    required: true
  - description: 'Optionally add the container name within the pod. By default, the
      command will execute in the first container listed in the pod definition.'
    label: Container Name
    name: container_name
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - configuration:
        command: ${option.command}
        container: ${option.container_name}
        name: ${option.pod_name}
        namespace: ${option.namespace}
        shell: /bin/bash
        verify_ssl: 'false'
      description: Execute Command
      nodeStep: true
      type: Kubernetes-Execute-Step
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: b02ca591-7605-4e1a-abf9-ce54d874d336

