- defaultTab: nodes
  description: |-
    Retrieves last 10 logs from an individual Pod in a specific Namespace.

    This Job retrieves the most recent logs from a specific Kubernetes Pod.  You can change the number of log-lines by modifying the `--tail` flag in the **Remote Command** step.

    If using PagerDuty Runbook Automation (SaaS), then this Job is designed to be run on an [**Enterprise Runner**](https://docs.rundeck.com/docs/administration/runner/#architecture). Follow the documentation and install the Runner in a location that can communicate with your Kubernetes cluster.
  executionEnabled: true
  group: Kubernetes
  id: 2cf722f5-8f18-4bfe-8300-d5e700656bb3
  loglevel: INFO
  name: Tail Logs from Individual Kubernetes Pod
  nodeFilterEditable: false
  options:
  - description: Namespace within the Kubernetes Cluster where the Pod resides.
    label: Kubernetes Namespace
    name: namespace
    required: true
    value: default
  - description: |-
      ID of the PagerDuty incident that should receive the diagnostics queried from this automation.
      This field is **_not_** required to invoke this Job.
    label: PagerDuty Incident ID
    name: pd_incident_id
  - description: Name of the kubernetes pod
    label: Pod Name
    name: pod_name
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: 'Retrieve Logs '
      exec: kubectl logs pod ${option.pod_name} -n ${option.namespace} --tail=10
      plugins:
        LogFilter:
        - config:
            captureMultipleKeysValues: 'false'
            hideOutput: 'false'
            logData: 'true'
            name: recent_pod_logs
            regex: (.*)
          type: key-value-data-multilines
    - configuration:
        api_token: keys/project/automated-diagnostics/pd-api-token
        incident_id: ${option.pd_incident_id}
        note: Recent Kubernetes Pod Logs:\n ${data.recent_pod_logs*}
      description: Send Diagnostics to PagerDuty
      errorhandler:
        configuration:
          text: Please provide PagerDuty API token and Incident ID to send diagnostics
            to Incident.
        keepgoingOnSuccess: true
        nodeStep: false
        type: progress-badge
      nodeStep: false
      type: pd-note-step
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: 2cf722f5-8f18-4bfe-8300-d5e700656bb3

