- defaultTab: nodes
  description: |-
    Retrieves last 10 logs from a specific Kubernetes Pod.

    This Job retrieves the most recent logs from a specific Kubernetes Pod.  You can change the number of log-lines by modifying the `--tail` flag in the **Remote Command** step.
  executionEnabled: true
  group: Kubernetes
  id: 8f9cfa59-8d50-4d46-9dc4-ab3ce01c255e
  loglevel: INFO
  name: Tail Logs from Individual Kubernetes Pod
  nodeFilterEditable: false
  options:
  - description: Name of the kubernetes pod
    label: Pod Name
    name: pod_name
    required: true
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: 'Retrieve Logs '
      exec: kubectl logs pod ${option.pod_name} --tail=10
    keepgoing: false
    strategy: node-first
  tags: kubernetes
  uuid: 8f9cfa59-8d50-4d46-9dc4-ab3ce01c255e

